# Generated by Django 3.1 on 2020-08-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oligoshell.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('comments', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Ordered')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order number',
                'verbose_name_plural': 'Orders',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_name', models.CharField(max_length=50, validators=[oligoshell.validators.validate_seq_name_regex], verbose_name='Name')),
                ('sequence', models.CharField(max_length=300, validators=[oligoshell.validators.validate_sequence_regex, oligoshell.validators.validate_modifications], verbose_name="Sequence, 5'->3'")),
                ('scale', models.CharField(choices=[('50 nmol', '50 nmol'), ('200 nmol', '200 nmol'), ('1 umol', '1 umol')], default='50 nmol', max_length=20, verbose_name='Synthesis Scale')),
                ('appearance_requested', models.CharField(choices=[('20 mM', '20 mM'), ('100 mM', '100 mM'), ('Freeze-dried', 'Freeze-dried')], default='20 mM', max_length=20, verbose_name='Appearance Requested')),
                ('purification_requested', models.CharField(choices=[('OPC', 'OPC'), ('RP-HPLC', 'RP-HPLC'), ('IEX-HPLC', 'IEX-HPLC'), ('PAGE', 'PAGE'), ('PAGE + HPLC', 'PAGE + HPLC'), ('Company Recommended', 'Company Recommended')], default='OPC', max_length=30, verbose_name='Purification Requested')),
                ('epsilon260', models.IntegerField(blank=True, null=True, verbose_name='Extinction Coefficient')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Sequence Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Sequence Updated')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='oligoshell.order')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Purification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Q', max_length=50, verbose_name='Purification Name')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Purification Created')),
                ('pur_seqs', models.ManyToManyField(related_name='purifications', to='oligoshell.Sequence')),
            ],
            options={
                'verbose_name': 'Purification',
                'verbose_name_plural': 'Purifications',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='user/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Batch Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Batch Created')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('sequences2synthesis', models.ManyToManyField(related_name='batches', to='oligoshell.Sequence', verbose_name='Sequences to be Synthesized')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['pk'],
            },
        ),
    ]
