# Generated by Django 3.1 on 2020-08-15 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Ordered')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order number',
                'verbose_name_plural': 'Orders',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name should contain letters, numbers and special characters  _ ( )', regex='^[-a-zA-Z0-9_()]+$')], verbose_name='Name')),
                ('sequence', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Sequence should contain A/C/G/T, degenerated bases W/S/M/K/R/Y/B/D/H/V/N, and modifications e.g. [FAM], [BHQ1] etc.', regex='^(((\\[[-\\._a-zA-Z0-9]+\\])*?[aAcCgGtTwWsSmMkKrRyYbBdDhHvVnN]*?)*?)$')], verbose_name="Sequence, 5'->3'")),
                ('scale', models.CharField(choices=[('50 nmol', '50 nmol'), ('200 nmol', '200 nmol'), ('1 umol', '1 umol')], default='50 nmol', max_length=20)),
                ('appearance_requested', models.CharField(choices=[('20 mM', '20 mM'), ('100 mM', '100 mM'), ('Freeze-dried', 'Freeze-dried')], default='20 mM', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='oligoshell.order')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'ordering': ['pk'],
            },
        ),
    ]
