# Generated by Django 3.1 on 2020-08-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_name', models.CharField(max_length=50, verbose_name='Name')),
                ('sequence', models.CharField(max_length=300, verbose_name="Sequence, 5'->3'")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'ordering': ['pk'],
            },
        ),
    ]
