# Generated by Django 3.1 on 2020-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='qu', max_length=50),
        ),
    ]
