# Generated by Django 3.1 on 2020-08-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purification',
            name='title',
            field=models.CharField(choices=[('OPC', 'OPC'), ('RP-HPLC', 'RP-HPLC'), ('IEX-HPLC', 'IEX-HPLC'), ('PAGE', 'PAGE')], default='OPC', max_length=50, verbose_name='Purification Name'),
        ),
    ]
