# Generated by Django 3.1 on 2020-08-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0002_auto_20200823_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='purification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Purification Created'),
        ),
        migrations.AlterField(
            model_name='purification',
            name='pur_seqs',
            field=models.ManyToManyField(related_name='purifications', to='oligoshell.Sequence', verbose_name='Sequences for Purification'),
        ),
        migrations.AlterField(
            model_name='purification',
            name='title',
            field=models.CharField(choices=[('OPC', 'OPC'), ('RP-HPLC', 'RP-HPLC'), ('IEX-HPLC', 'IEX-HPLC'), ('PAGE', 'PAGE')], default='OPC', max_length=50, verbose_name='Purification Method'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='appearance_requested',
            field=models.CharField(choices=[('20 mM', '20 mM'), ('100 mM', '100 mM'), ('Freeze-dried', 'Freeze-dried')], default='20 mM', max_length=20, verbose_name='Appearance'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='purification_requested',
            field=models.CharField(choices=[('OPC', 'OPC'), ('RP-HPLC', 'RP-HPLC'), ('IEX-HPLC', 'IEX-HPLC'), ('PAGE', 'PAGE'), ('PAGE + HPLC', 'PAGE + HPLC'), ('Company Recommended', 'Company Recommended')], default='OPC', max_length=30, verbose_name='Purification'),
        ),
    ]
