# Generated by Django 3.1 on 2020-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0002_sequence_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='scale',
            field=models.CharField(choices=[('50 nmol', '50 nmol'), ('200 nmol', '200 nmol'), ('1 umol', '1 umol')], default='50 nmol', max_length=20),
        ),
    ]
