# Generated by Django 3.1 on 2020-08-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0003_auto_20200825_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='absorbance260',
            field=models.FloatField(blank=True, null=True, verbose_name='Absorbance at 260 nm'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentration, uM'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Sequence Complete'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Volume, mL'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
