# Generated by Django 3.1 on 2020-08-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0003_auto_20200815_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=50, verbose_name='Customer Name'),
        ),
    ]
