# Generated by Django 3.1 on 2020-08-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0004_auto_20200815_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seqs', to='oligoshell.order'),
        ),
    ]
