# Generated by Django 3.1 on 2020-08-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0005_auto_20200815_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='oligoshell.order'),
        ),
    ]
