# Generated by Django 3.1 on 2020-08-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0005_auto_20200826_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='oligoshell.order'),
        ),
    ]
