# Generated by Django 3.1 on 2020-08-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0006_auto_20200826_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='synthesized',
            field=models.BooleanField(default=False, verbose_name='Sequence Synthesized'),
        ),
    ]
