# Generated by Django 3.1 on 2020-08-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0007_sequence_synthesized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='synthesized',
        ),
    ]
