# Generated by Django 3.1 on 2020-08-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0008_remove_sequence_synthesized'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='synthesized',
            field=models.BooleanField(default=False, verbose_name='Sequence Synthesized'),
        ),
    ]
