# Generated by Django 3.1 on 2020-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0009_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='epsilon260',
            field=models.IntegerField(default=0, verbose_name='Extinction Coefficient'),
        ),
    ]
