# Generated by Django 3.1 on 2020-10-15 20:23

from django.db import migrations, models
import oligoshell.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0009_sequence_synthesized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq_name',
            field=models.CharField(max_length=50, validators=[oligoshell.validators.validate_seq_name_regex], verbose_name='Sequence Name'),
        ),
    ]
