# Generated by Django 3.1 on 2020-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0010_sequence_epsilon260'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='epsilon260',
            field=models.IntegerField(verbose_name='Extinction Coefficient'),
        ),
    ]
