# Generated by Django 3.1 on 2020-08-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0012_auto_20200819_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='epsilon260',
            field=models.IntegerField(default=0, verbose_name='Extinction Coefficient'),
        ),
    ]
