# Generated by Django 3.1 on 2020-08-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0013_auto_20200819_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='epsilon260',
            field=models.IntegerField(verbose_name='Extinction Coefficient'),
        ),
    ]
