# Generated by Django 3.1 on 2020-08-20 19:18

from django.db import migrations, models
import oligoshell.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0014_auto_20200819_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq_name',
            field=models.CharField(max_length=50, validators=[oligoshell.validators.validate_seq_name_regex], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.CharField(max_length=300, validators=[oligoshell.validators.validate_sequence_regex], verbose_name="Sequence, 5'->3'"),
        ),
    ]
