# Generated by Django 3.1 on 2020-08-20 20:34

from django.db import migrations, models
import oligoshell.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0015_auto_20200820_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.CharField(max_length=300, validators=[oligoshell.validators.validate_sequence_regex, oligoshell.validators.validate_modifications], verbose_name="Sequence, 5'->3'"),
        ),
    ]
