# Generated by Django 3.1 on 2020-08-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0016_auto_20200820_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='chosen',
            field=models.BooleanField(default=False, verbose_name='Chosen'),
        ),
    ]
