# Generated by Django 3.1 on 2020-08-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0017_sequence_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='chosen',
        ),
    ]
