# Generated by Django 3.1 on 2020-08-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligoshell', '0020_auto_20200823_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_txt',
        ),
    ]
